In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from collections import Counter
import re

# Plot style
sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 5)

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 200)

In [2]:
DATA_PATH = r"C:\Users\Anwender\humor-project\data\labels\hahackathon_train.csv"

df_haha = pd.read_csv(DATA_PATH)

print("Shape:", df_haha.shape)
df_haha.head()

Shape: (8000, 6)

,id,text,is_humor,humor_rating,humor_controversy,offense_rating
0,1,TENNESSEE: We're the best state. Nobody even comes close. *Elevennessee walks into the room* TENNESSEE: Oh shit...,1,2.42,1.0,0.2
1,2,"A man inserted an advertisement in the classifieds ""Wife Wanted"". The next day, he received 1000 of replies, all reading: ""You can have mine."" Free delivery also available at your door step",1,2.50,1.0,1.1
2,3,How many men does it take to open a can of beer? None. It should be open by the time she brings it to the couch.,1,1.95,0.0,2.4
3,4,Told my mom I hit 1200 Twitter followers. She pointed out how my brother owns a house and I'm wanted by several collection agencies. Oh ma!,1,2.11,1.0,0.0
4,5,Roses are dead. Love is fake. Weddings are basically funerals with cake.,1,2.78,0.0,0.1

In [9]:
df = pd.read_csv(r"C:\Users\Anwender\humor-project\data\labels\hahackathon_train.csv")

df = df.rename(columns={"is_humor": "y_cls", "humor_rating": "y_reg"})

# 1) Drop rows where text missing
df = df.dropna(subset=["text"])

# 2) y_cls: if missing -> -1 (mask)
df["y_cls"] = df["y_cls"].fillna(-1).astype(int)

# 3) y_reg: if missing -> -1.0 (mask)
df["y_reg"] = df["y_reg"].fillna(-1.0).astype(float)

# Ensure plain scalar floats/ints (no lists)
df["y_reg"] = df["y_reg"].astype(float)
df["y_cls"] = df["y_cls"].astype(int)

df.head()

,id,text,y_cls,y_reg,humor_controversy,offense_rating
0,1,TENNESSEE: We're the best state. Nobody even comes close. *Elevennessee walks into the room* TENNESSEE: Oh shit...,1,2.42,1.0,0.2
1,2,"A man inserted an advertisement in the classifieds ""Wife Wanted"". The next day, he received 1000 of replies, all reading: ""You can have mine."" Free delivery also available at your door step",1,2.50,1.0,1.1
2,3,How many men does it take to open a can of beer? None. It should be open by the time she brings it to the couch.,1,1.95,0.0,2.4
3,4,Told my mom I hit 1200 Twitter followers. She pointed out how my brother owns a house and I'm wanted by several collection agencies. Oh ma!,1,2.11,1.0,0.0
4,5,Roses are dead. Love is fake. Weddings are basically funerals with cake.,1,2.78,0.0,0.1